# Generated by Django 6.0.4 on 2026-04-15 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('writing', 'Письмо'), ('notebooks', 'Тетради и блокноты'), ('bags', 'Рюкзаки и сумки'), ('art', 'Творчество'), ('office', 'Офис')], max_length=20)),
                ('name_ru', models.CharField(max_length=200)),
                ('name_ky', models.CharField(max_length=200)),
                ('desc_ru', models.TextField()),
                ('desc_ky', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('badge', models.CharField(blank=True, choices=[('new', 'Новинка'), ('sale', 'Скидка'), ('', 'Нет')], default='', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
    ]
