# Generated by Django 6.0.4 on 2026-04-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='emoji',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
